# Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wso2ei-scalable-bps-deployment
spec:
  replicas: 2
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: wso2ei-scalable-bps
    spec:
      containers:
      - name: wso2ei-scalable-bps
        image: docker.wso2.com/wso2ei-business-process:6.3.0
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - nc -z localhost 9445
          initialDelaySeconds: 90
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - nc -z localhost 9445
          initialDelaySeconds: 90
          periodSeconds: 10
        imagePullPolicy: Always
        ports:
        - containerPort: 9765
          protocol: TCP
        - containerPort: 9445
          protocol: TCP
        volumeMounts:
        - name: bps-conf
          mountPath: /home/wso2carbon/kubernetes-volumes/business-process/conf
        - name: bps-conf-axis2
          mountPath: /home/wso2carbon/kubernetes-volumes/business-process/conf/axis2
        - name: bps-conf-datasources
          mountPath: /home/wso2carbon/kubernetes-volumes/business-process/conf/datasources
        - name: bps-conf-etc
          mountPath: /home/wso2carbon/kubernetes-volumes/business-process/conf/etc
        - name: bps-server-share-volume
          mountPath: /home/wso2carbon/wso2ei-6.4.0/wso2/business-process/repository/deployment/server
      imagePullSecrets:
      - name: wso2creds
      serviceAccountName: "wso2svc-account"
      volumes:
      - name: bps-conf
        configMap:
          name: bps-conf
      - name: bps-conf-axis2
        configMap:
          name: bps-conf-axis2
      - name: bps-conf-datasources
        configMap:
          name: bps-conf-datasources
      - name: bps-conf-etc
        configMap:
          name: bps-conf-etc
      - name: bps-server-share-volume
        persistentVolumeClaim:
          claimName: scalable-bps-shared-volume-claim
